name: Connector Validation

defaults:
  run:
    shell: bash

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Validate connector strucure
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v22.2
        with:
          files: |           
            connectors/**      
      - name: Connectors validation
        run: |
          ids=(${{ steps.changed-files.outputs.all_changed_files }});
          if [ ${#ids[@]} -eq 0 ]; then
            echo "No updated connector"
          else            
            cd ${{ github.workspace }}/scripts/
            id="${ids[@]}";
            go run . "validate-connector" ${{ github.workspace }} connector.schema.json ${id// /" "}
            cd ${{ github.workspace }}
          fi    
